### PR TITLE
Add disposal fields support

### PR DESCRIPTION
**Pull request by dkumanov**
Expected Approvals: 2

### CODE REVIEW

**Comment by teodoradobreva** [comment]
I'm sorry but it's easier to comment here. Is avsluttetDato in Dokument M602 or M603?

**Comment by teodoradobreva** [comment]
No other comments.

**Comment by dkumanov** [comment]
> I'm sorry but it's easier to comment here. Is avsluttetDato in Dokument M602 or M603?

Fixed with https://github.com/documaster/noark5-web-services/pull/52/commits/c363b95ee83498b7b7d437eb194a10ebdedf0aef

**Review by teodoradobreva — APPROVED** [review]

**Review by ivaylomitrev — APPROVED** [review]

**Comment by dkumanov** [comment]
I made the second commit more descriptive and squashed the 4th commit into the 3rd one. No other changes. Will merge in a bit.

**Pull request merged**
